db_domains = {'adj_factor_item': {},
              'basic_stock_info_item': {},
              'basic_trading_info_item': {},
              'daily_basic_item': {},
              'industrial_classfication_member_item': {},
              'industrial_classification_item': {},
              'industry_classificatoin_meta_item': {},
              'institution_hold_item': {},
              'ma_target_asset': {},
              'ma_target_asset_group': {},
              'market_width_item': {},
              'meta_data_item': {},
              'momentum_daily_rank_jf_item': {},
              'momentum_daily_rank_pick_jf_item': {},
              'trade_calendar_item': {},
              'trading_info_update_meta_item': {},
              'us_ccsa_item': {},
              'us_icsa_item': {},
              'us_wei_item': {}
              }
